"""add deployments table

Revision ID: 499042db27c8
Revises: 0b5e5c2a04f7
Create Date: 2025-11-21 08:15:18.349587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '499042db27c8'
down_revision: Union[str, Sequence[str], None] = '0b5e5c2a04f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_constraint('deployments_build_id_fkey', 'deployments', type_='foreignkey')
    op.drop_column('deployments', 'traffic_percent')
    op.drop_column('deployments', 'revision_name')
    op.drop_column('deployments', 'service_name')
    op.drop_column('deployments', 'image_uri')
    op.drop_index(op.f('ix_builds_build_id'), table_name='builds')
    op.drop_index(op.f('ix_builds_id'), table_name='builds')
    op.drop_table('builds')
    op.add_column('deployments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('deployments', sa.Column('name', sa.String(), nullable=False))
    op.add_column('deployments', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('deployments', sa.Column('region', sa.String(), nullable=False))
    op.add_column('deployments', sa.Column('dockerfile_path', sa.String(), nullable=True))
    op.add_column('deployments', sa.Column('source_gcs_uri', sa.String(), nullable=True))
    op.add_column('deployments', sa.Column('build_logs_url', sa.String(), nullable=True))
    op.add_column('deployments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('deployments', 'build_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'deployments', 'users', ['user_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('image_uri', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('deployments', sa.Column('service_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('deployments', sa.Column('revision_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('deployments', sa.Column('traffic_percent', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'deployments', type_='foreignkey')
    op.create_foreign_key(op.f('deployments_build_id_fkey'), 'deployments', 'builds', ['build_id'], ['id'])
    op.alter_column('deployments', 'build_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('deployments', 'updated_at')
    op.drop_column('deployments', 'build_logs_url')
    op.drop_column('deployments', 'source_gcs_uri')
    op.drop_column('deployments', 'dockerfile_path')
    op.drop_column('deployments', 'region')
    op.drop_column('deployments', 'image_url')
    op.drop_column('deployments', 'name')
    op.drop_column('deployments', 'user_id')
    op.create_table('builds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('notebook_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('build_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source_bucket', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_object', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('log_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], name=op.f('builds_notebook_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('builds_pkey'))
    )
    op.create_index(op.f('ix_builds_id'), 'builds', ['id'], unique=False)
    op.create_index(op.f('ix_builds_build_id'), 'builds', ['build_id'], unique=True)
    # ### end Alembic commands ###
