"""add deployment metrics

Revision ID: 6b590d70e7ce
Revises: 499042db27c8
Create Date: 2025-11-21 09:36:59.868063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b590d70e7ce'
down_revision: Union[str, Sequence[str], None] = '499042db27c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deployment_id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_metrics_id'), 'deployment_metrics', ['id'], unique=False)
    op.add_column('deployments', sa.Column('build_duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'build_duration')
    op.drop_index(op.f('ix_deployment_metrics_id'), table_name='deployment_metrics')
    op.drop_table('deployment_metrics')
    # ### end Alembic commands ###
